version: '3.7'

services:
  postgres:
    restart: on-failure
    image: docker.io/postgres:15.1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d forester -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=forester
    volumes:
      - ${DATA_DIR:-./data}/postgres:/var/lib/postgresql/data:Z
    expose:
      - 5432

  controller:
    environment:
      - IMAGES_DIR=/images
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      - /forester-controller
    image: quay.io/forester/controller:latest
    ports:
      - ${EXPOSED_APP_PORT:-8000}:${APP_PORT:-8000}
      - ${EXPOSED_TFTP_PORT:-6969}:${TFTP_PORT:-6969}
    volumes:
      - ${DATA_DIR:-./data}/images:/images:Z
