CREATE TABLE images
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (name <> '') UNIQUE
);

CREATE TABLE appliances
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (name <> '') UNIQUE,
  kind SMALLINT NOT NULL CHECK (kind != 0),
  uri TEXT NOT NULL CHECK (uri <> '')
);

CREATE TABLE systems
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL DEFAULT random_name() UNIQUE,
  appliance_id BIGINT REFERENCES appliances(id),
  uid TEXT CHECK (uid <> '') NOT NULL DEFAULT '',
  hwaddrs MACADDR[] NOT NULL CHECK (array_length(hwaddrs, 1) > 0),
  facts JSONB NOT NULL,
  acquired BOOLEAN NOT NULL DEFAULT FALSE,
  acquired_at TIMESTAMP NOT NULL DEFAULT '0001-01-01 00:00:00',
  image_id BIGINT REFERENCES images(id),
  comment TEXT DEFAULT ''
);

CREATE INDEX idx_systems_mac ON systems USING GIN(hwaddrs);
