CREATE TABLE snippets
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (name <> '') UNIQUE,
  kind SMALLINT NOT NULL CHECK (kind != 0),
  body TEXT NOT NULL CHECK (body <> '')
);

CREATE INDEX idx_snippets_kind ON snippets(kind);
