CREATE TABLE snippets
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (name <> '') UNIQUE,
  kind SMALLINT NOT NULL CHECK (kind != 0),
  body TEXT NOT NULL CHECK (body <> '')
);

CREATE INDEX idx_snippets_kind ON snippets(kind);

CREATE TABLE systems_snippets
(
  system_id BIGINT REFERENCES systems(id) ON DELETE CASCADE ON UPDATE CASCADE,
  snippet_id BIGINT REFERENCES snippets(id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY(system_id, snippet_id)
)
