CREATE EXTENSION pgcrypto;

CREATE TABLE installations
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid(),
  state SMALLINT NOT NULL CHECK (state != 0) DEFAULT 100,
  valid_until TIMESTAMP NOT NULL DEFAULT current_timestamp + interval '3 hours',
  queued_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
  system_id BIGINT NOT NULL REFERENCES systems(id) ON DELETE CASCADE ON UPDATE CASCADE,
  image_id BIGINT NOT NULL REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE,
  snippet_text TEXT NOT NULL DEFAULT '',
  kickstart_override TEXT NOT NULL DEFAULT '',
  comment TEXT NOT NULL DEFAULT ''
);

CREATE INDEX idx_installations_valid_until ON installations(valid_until);

ALTER TABLE systems
  DROP COLUMN install_uuid,
  DROP COLUMN image_id;

DROP TABLE systems_snippets;

CREATE TABLE installations_snippets
(
  installation_id BIGINT REFERENCES installations(id) ON DELETE CASCADE ON UPDATE CASCADE,
  snippet_id BIGINT REFERENCES snippets(id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY(installation_id, snippet_id)
)
