CREATE TABLE images
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (name <> '') UNIQUE
);

CREATE TABLE systems
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL DEFAULT random_name(),
  hwaddrs MACADDR[] NOT NULL CHECK (array_length(hwaddr, 1) > 0),
  facts JSONB NOT NULL,
  acquired BOOLEAN NOT NULL,
  acquired_at TIME NOT NULL,
  image_id BIGINT REFERENCES images(id),
  comment TEXT
);

CREATE INDEX idx_systems_mac ON systems USING GIN(hwaddr);
